/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    jobs: Job;
    companies: Company;
    applications: Application;
    'saved-jobs': SavedJob;
    'job-alerts': JobAlert;
    'notification-history': NotificationHistory;
    'sarkari-updates': SarkariUpdate;
    results: Result;
    'admit-cards': AdmitCard;
    'answer-keys': AnswerKey;
    syllabuses: Syllabuse;
    'govt-notifications': GovtNotification;
    media: Media;
    resumes: Resume;
    'job-sources': JobSource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'saved-jobs': SavedJobsSelect<false> | SavedJobsSelect<true>;
    'job-alerts': JobAlertsSelect<false> | JobAlertsSelect<true>;
    'notification-history': NotificationHistorySelect<false> | NotificationHistorySelect<true>;
    'sarkari-updates': SarkariUpdatesSelect<false> | SarkariUpdatesSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    'admit-cards': AdmitCardsSelect<false> | AdmitCardsSelect<true>;
    'answer-keys': AnswerKeysSelect<false> | AnswerKeysSelect<true>;
    syllabuses: SyllabusesSelect<false> | SyllabusesSelect<true>;
    'govt-notifications': GovtNotificationsSelect<false> | GovtNotificationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resumes: ResumesSelect<false> | ResumesSelect<true>;
    'job-sources': JobSourcesSelect<false> | JobSourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'system-settings': SystemSetting;
  };
  globalsSelect: {
    'system-settings': SystemSettingsSelect<false> | SystemSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'employer' | 'jobseeker';
  phoneNumber?: string | null;
  preferences?: {
    emailAlerts?: boolean | null;
    inAppAlerts?: boolean | null;
  };
  alertUnsubscribeToken?: string | null;
  globalUnsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * Effective display status for the frontend.
   */
  status?: ('draft' | 'open' | 'closing soon' | 'closed') | null;
  /**
   * If checked, automated expiry scripts will ignore this job.
   */
  statusLock?: boolean | null;
  isArchived?: boolean | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isPossibleDuplicate?: boolean | null;
  postingContextToken?: string | null;
  type: 'private' | 'government';
  isVerified?: boolean | null;
  verifiedDate?: string | null;
  owner?: (number | null) | User;
  verifiedBy?: (number | null) | User;
  officialSourceUrl?: string | null;
  linkHealth?: ('Healthy' | 'Warning' | 'Broken') | null;
  lastCheckedAt?: string | null;
  sourceRegistry?: (number | null) | JobSource;
  discoveredAt?: string | null;
  lastVerifiedAt?: string | null;
  rankingScore?: number | null;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  location: string;
  salary?: string | null;
  /**
   * URL where candidate should apply directly (Govt portal or Company career page)
   */
  applyUrl?: string | null;
  dynamicSections?:
    | (
        | {
            dates?:
              | {
                  event: string;
                  date: string;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ImportantDates';
          }
        | {
            fees?:
              | {
                  category: string;
                  amount: string;
                  id?: string | null;
                }[]
              | null;
            paymentMode?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ApplicationFee';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'VacancyTable';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'EducationalQualification';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'AgeLimit';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'SelectionProcess';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ExamDetails';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'PhysicalStandards';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'MedicalStandards';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'SalaryPayScale';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'Experience';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'DocumentsRequired';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'HowToApply';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'HowToFillForm';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ImportantInstructions';
          }
        | {
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ImportantLinks';
          }
        | {
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'CustomSection';
          }
        | {
            title: string;
            description?: string | null;
            columns: {
              heading: string;
              id?: string | null;
            }[];
            rows?:
              | {
                  cells?:
                    | {
                        value?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'DynamicMatrix';
          }
        | {
            title: string;
            listItems: {
              key: string;
              value?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'KeyValueList';
          }
      )[]
    | null;
  govtCategory?:
    ('SSC' | 'UPSC' | 'Railway' | 'Banking' | 'Defence' | 'Police' | 'Teaching' | 'State Government' | 'Other') | null;
  organization?: string | null;
  advertisementNumber?: string | null;
  vacancies?: number | null;
  qualification?: string | null;
  ageLimit?: string | null;
  applicationFee?: string | null;
  applicationStartDate?: string | null;
  lastDate?: string | null;
  correctionDate?: string | null;
  examDate?: string | null;
  selectionProcess?: string | null;
  requiredDocuments?: string | null;
  officialNotificationUrl?: string | null;
  officialWebsiteUrl?: string | null;
  privateCategory?:
    | (
        | 'IT & Software'
        | 'Engineering'
        | 'Finance'
        | 'Sales'
        | 'Marketing'
        | 'Healthcare'
        | 'BPO'
        | 'Internship'
        | 'Remote'
        | 'Other'
      )
    | null;
  company?: (number | null) | Company;
  companyWebsiteUrl?: string | null;
  experience?: string | null;
  workMode?: ('On-site' | 'Hybrid' | 'Remote') | null;
  jobType?: ('Full Time' | 'Part Time' | 'Contract' | 'Internship') | null;
  skills?: string | null;
  applicationMethod?: 'external' | null;
  views?: number | null;
  applyClicks?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-sources".
 */
export interface JobSource {
  id: number;
  name: string;
  type: 'government' | 'private';
  /**
   * The homepage or primary career portal URL
   */
  sourceUrl: string;
  /**
   * Machine-readable endpoint like RSS or JSON API
   */
  feedUrl?: string | null;
  /**
   * Must be verified to allow automated imports
   */
  isVerified?: boolean | null;
  healthStatus?: ('Healthy' | 'Warning' | 'Broken') | null;
  integrationType?: ('Manual' | 'RSS' | 'API_Webhook' | 'Scraper') | null;
  lastCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Used for company profile URL.
   */
  slug?: string | null;
  isPublished?: boolean | null;
  /**
   * Admin-only control. Does not imply endorsement.
   */
  isVerified?: boolean | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isArchived?: boolean | null;
  isPossibleDuplicate?: boolean | null;
  logo?: (number | null) | Media;
  /**
   * e.g. IT & Software, Banking & Finance, Healthcare, Real Estate, etc.
   */
  industry: string;
  location: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  companySize?:
    | ('1-10' | '11-50' | '51-200' | '201-500' | '501-1000' | '1001-5000' | '5001-10000' | '10000+' | 'Not specified')
    | null;
  websiteUrl?: string | null;
  careerUrl?: string | null;
  openPositions?: number | null;
  owner?: (number | null) | User;
  /**
   * Employers who have access to manage this company.
   */
  members?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  job: number | Job;
  applicant: number | User;
  status: 'draft' | 'applied' | 'interview' | 'selected' | 'rejected' | 'withdrawn';
  notes?: string | null;
  statusHistory?:
    | {
        previousStatus?: string | null;
        newStatus?: string | null;
        changedBy?: (number | null) | User;
        changedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-jobs".
 */
export interface SavedJob {
  id: number;
  user: number | User;
  job: number | Job;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-alerts".
 */
export interface JobAlert {
  id: number;
  user: number | User;
  name: string;
  type: 'government' | 'private';
  isActive?: boolean | null;
  govtCategory?:
    ('SSC' | 'UPSC' | 'Railway' | 'Banking' | 'Defence' | 'Police' | 'Teaching' | 'State Government' | 'Other') | null;
  state?: string | null;
  privateCategory?:
    | (
        | 'IT & Software'
        | 'Engineering'
        | 'Finance'
        | 'Sales'
        | 'Marketing'
        | 'Healthcare'
        | 'BPO'
        | 'Internship'
        | 'Remote'
        | 'Other'
      )
    | null;
  workMode?: ('On-site' | 'Hybrid' | 'Remote') | null;
  experience?: string | null;
  location?: string | null;
  qualification?: string | null;
  keywords?: string | null;
  lastMatchedAt?: string | null;
  lastNotifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-history".
 */
export interface NotificationHistory {
  id: number;
  user: number | User;
  job: number | Job;
  jobAlert: number | JobAlert;
  status: 'draft' | 'queued' | 'processing' | 'sent' | 'skipped' | 'failed';
  channels?: ('in-app' | 'email' | 'push')[] | null;
  attempts?: number | null;
  lastAttemptAt?: string | null;
  nextAttemptAt?: string | null;
  errorLog?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sarkari-updates".
 */
export interface SarkariUpdate {
  id: number;
  title: string;
  category: 'Result' | 'Admit Card' | 'Latest Jobs' | 'Answer Key' | 'Syllabus' | 'Admission' | 'Important';
  link: string;
  highlight?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  title: string;
  /**
   * URL slug (e.g., ssc-cgl-result-2026)
   */
  slug: string;
  organization: string;
  examName: string;
  resultDate?: string | null;
  status: 'draft' | 'Awaited' | 'Published';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link to the original Government Job/Recruitment (Optional)
   */
  relatedJob?: (number | null) | Job;
  officialUrl?: string | null;
  isVerified?: boolean | null;
  verifiedDate?: string | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isArchived?: boolean | null;
  verifiedBy?: (number | null) | User;
  officialSourceUrl?: string | null;
  linkHealth?: ('Healthy' | 'Warning' | 'Broken') | null;
  lastCheckedAt?: string | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admit-cards".
 */
export interface AdmitCard {
  id: number;
  title: string;
  /**
   * URL slug (e.g., ssc-cgl-admit-card-2026)
   */
  slug: string;
  organization: string;
  examName: string;
  examDate?: string | null;
  admitCardReleaseDate?: string | null;
  /**
   * Check to manually set the status instead of auto-calculating from dates.
   */
  overrideStatus?: boolean | null;
  status?: ('draft' | 'Upcoming' | 'Released' | 'Exam Completed') | null;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link to the original Government Job/Recruitment (Optional)
   */
  relatedJob?: (number | null) | Job;
  officialUrl?: string | null;
  isVerified?: boolean | null;
  verifiedDate?: string | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isArchived?: boolean | null;
  verifiedBy?: (number | null) | User;
  officialSourceUrl?: string | null;
  linkHealth?: ('Healthy' | 'Warning' | 'Broken') | null;
  lastCheckedAt?: string | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-keys".
 */
export interface AnswerKey {
  id: number;
  title: string;
  /**
   * URL slug (e.g., ssc-cgl-answer-key-2026)
   */
  slug: string;
  organization: string;
  examName: string;
  examDate?: string | null;
  answerKeyReleaseDate?: string | null;
  objectionStartDate?: string | null;
  objectionLastDate?: string | null;
  /**
   * Check to manually set the status instead of auto-calculating.
   */
  overrideStatus?: boolean | null;
  status?: ('draft' | 'Not Released' | 'Released' | 'Objection Open' | 'Objection Closed') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link to the original Government Job/Recruitment (Optional)
   */
  relatedJob?: (number | null) | Job;
  officialUrl?: string | null;
  isVerified?: boolean | null;
  verifiedDate?: string | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isArchived?: boolean | null;
  verifiedBy?: (number | null) | User;
  officialSourceUrl?: string | null;
  linkHealth?: ('Healthy' | 'Warning' | 'Broken') | null;
  lastCheckedAt?: string | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabuses".
 */
export interface Syllabuse {
  id: number;
  title: string;
  /**
   * URL slug (e.g., ssc-cgl-syllabus-2026)
   */
  slug: string;
  organization: string;
  subject?: string | null;
  examLevel?: string | null;
  qualification?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link to the original Government Job/Recruitment (Optional)
   */
  relatedJob?: (number | null) | Job;
  officialUrl?: string | null;
  isVerified?: boolean | null;
  verifiedDate?: string | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isArchived?: boolean | null;
  verifiedBy?: (number | null) | User;
  officialSourceUrl?: string | null;
  linkHealth?: ('Healthy' | 'Warning' | 'Broken') | null;
  lastCheckedAt?: string | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "govt-notifications".
 */
export interface GovtNotification {
  id: number;
  title: string;
  /**
   * URL slug (e.g., ssc-cgl-postponed-notice-2026)
   */
  slug: string;
  organization: string;
  date: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link to the original Government Job/Recruitment (Optional)
   */
  relatedJob?: (number | null) | Job;
  officialUrl?: string | null;
  isVerified?: boolean | null;
  verifiedDate?: string | null;
  verificationStatus?: ('Draft' | 'Under Review' | 'Verified' | 'Rejected') | null;
  isArchived?: boolean | null;
  verifiedBy?: (number | null) | User;
  officialSourceUrl?: string | null;
  linkHealth?: ('Healthy' | 'Warning' | 'Broken') | null;
  lastCheckedAt?: string | null;
  isPublished?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes".
 */
export interface Resume {
  id: number;
  user: number | User;
  isPrimary?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'saved-jobs';
        value: number | SavedJob;
      } | null)
    | ({
        relationTo: 'job-alerts';
        value: number | JobAlert;
      } | null)
    | ({
        relationTo: 'notification-history';
        value: number | NotificationHistory;
      } | null)
    | ({
        relationTo: 'sarkari-updates';
        value: number | SarkariUpdate;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'admit-cards';
        value: number | AdmitCard;
      } | null)
    | ({
        relationTo: 'answer-keys';
        value: number | AnswerKey;
      } | null)
    | ({
        relationTo: 'syllabuses';
        value: number | Syllabuse;
      } | null)
    | ({
        relationTo: 'govt-notifications';
        value: number | GovtNotification;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'resumes';
        value: number | Resume;
      } | null)
    | ({
        relationTo: 'job-sources';
        value: number | JobSource;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phoneNumber?: T;
  preferences?:
    | T
    | {
        emailAlerts?: T;
        inAppAlerts?: T;
      };
  alertUnsubscribeToken?: T;
  globalUnsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  status?: T;
  statusLock?: T;
  isArchived?: T;
  verificationStatus?: T;
  isPossibleDuplicate?: T;
  postingContextToken?: T;
  type?: T;
  isVerified?: T;
  verifiedDate?: T;
  owner?: T;
  verifiedBy?: T;
  officialSourceUrl?: T;
  linkHealth?: T;
  lastCheckedAt?: T;
  sourceRegistry?: T;
  discoveredAt?: T;
  lastVerifiedAt?: T;
  rankingScore?: T;
  title?: T;
  description?: T;
  location?: T;
  salary?: T;
  applyUrl?: T;
  dynamicSections?:
    | T
    | {
        ImportantDates?:
          | T
          | {
              dates?:
                | T
                | {
                    event?: T;
                    date?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ApplicationFee?:
          | T
          | {
              fees?:
                | T
                | {
                    category?: T;
                    amount?: T;
                    id?: T;
                  };
              paymentMode?: T;
              id?: T;
              blockName?: T;
            };
        VacancyTable?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        EducationalQualification?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        AgeLimit?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        SelectionProcess?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        ExamDetails?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        PhysicalStandards?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        MedicalStandards?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        SalaryPayScale?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        Experience?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        DocumentsRequired?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        HowToApply?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        HowToFillForm?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        ImportantInstructions?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        ImportantLinks?:
          | T
          | {
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        CustomSection?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        DynamicMatrix?:
          | T
          | {
              title?: T;
              description?: T;
              columns?:
                | T
                | {
                    heading?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        KeyValueList?:
          | T
          | {
              title?: T;
              listItems?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  govtCategory?: T;
  organization?: T;
  advertisementNumber?: T;
  vacancies?: T;
  qualification?: T;
  ageLimit?: T;
  applicationFee?: T;
  applicationStartDate?: T;
  lastDate?: T;
  correctionDate?: T;
  examDate?: T;
  selectionProcess?: T;
  requiredDocuments?: T;
  officialNotificationUrl?: T;
  officialWebsiteUrl?: T;
  privateCategory?: T;
  company?: T;
  companyWebsiteUrl?: T;
  experience?: T;
  workMode?: T;
  jobType?: T;
  skills?: T;
  applicationMethod?: T;
  views?: T;
  applyClicks?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isPublished?: T;
  isVerified?: T;
  verificationStatus?: T;
  isArchived?: T;
  isPossibleDuplicate?: T;
  logo?: T;
  industry?: T;
  location?: T;
  description?: T;
  companySize?: T;
  websiteUrl?: T;
  careerUrl?: T;
  openPositions?: T;
  owner?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  job?: T;
  applicant?: T;
  status?: T;
  notes?: T;
  statusHistory?:
    | T
    | {
        previousStatus?: T;
        newStatus?: T;
        changedBy?: T;
        changedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-jobs_select".
 */
export interface SavedJobsSelect<T extends boolean = true> {
  user?: T;
  job?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-alerts_select".
 */
export interface JobAlertsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  type?: T;
  isActive?: T;
  govtCategory?: T;
  state?: T;
  privateCategory?: T;
  workMode?: T;
  experience?: T;
  location?: T;
  qualification?: T;
  keywords?: T;
  lastMatchedAt?: T;
  lastNotifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-history_select".
 */
export interface NotificationHistorySelect<T extends boolean = true> {
  user?: T;
  job?: T;
  jobAlert?: T;
  status?: T;
  channels?: T;
  attempts?: T;
  lastAttemptAt?: T;
  nextAttemptAt?: T;
  errorLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sarkari-updates_select".
 */
export interface SarkariUpdatesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  link?: T;
  highlight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  examName?: T;
  resultDate?: T;
  status?: T;
  description?: T;
  relatedJob?: T;
  officialUrl?: T;
  isVerified?: T;
  verifiedDate?: T;
  verificationStatus?: T;
  isArchived?: T;
  verifiedBy?: T;
  officialSourceUrl?: T;
  linkHealth?: T;
  lastCheckedAt?: T;
  isPublished?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admit-cards_select".
 */
export interface AdmitCardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  examName?: T;
  examDate?: T;
  admitCardReleaseDate?: T;
  overrideStatus?: T;
  status?: T;
  instructions?: T;
  relatedJob?: T;
  officialUrl?: T;
  isVerified?: T;
  verifiedDate?: T;
  verificationStatus?: T;
  isArchived?: T;
  verifiedBy?: T;
  officialSourceUrl?: T;
  linkHealth?: T;
  lastCheckedAt?: T;
  isPublished?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-keys_select".
 */
export interface AnswerKeysSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  examName?: T;
  examDate?: T;
  answerKeyReleaseDate?: T;
  objectionStartDate?: T;
  objectionLastDate?: T;
  overrideStatus?: T;
  status?: T;
  description?: T;
  relatedJob?: T;
  officialUrl?: T;
  isVerified?: T;
  verifiedDate?: T;
  verificationStatus?: T;
  isArchived?: T;
  verifiedBy?: T;
  officialSourceUrl?: T;
  linkHealth?: T;
  lastCheckedAt?: T;
  isPublished?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabuses_select".
 */
export interface SyllabusesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  subject?: T;
  examLevel?: T;
  qualification?: T;
  content?: T;
  relatedJob?: T;
  officialUrl?: T;
  isVerified?: T;
  verifiedDate?: T;
  verificationStatus?: T;
  isArchived?: T;
  verifiedBy?: T;
  officialSourceUrl?: T;
  linkHealth?: T;
  lastCheckedAt?: T;
  isPublished?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "govt-notifications_select".
 */
export interface GovtNotificationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  organization?: T;
  date?: T;
  description?: T;
  relatedJob?: T;
  officialUrl?: T;
  isVerified?: T;
  verifiedDate?: T;
  verificationStatus?: T;
  isArchived?: T;
  verifiedBy?: T;
  officialSourceUrl?: T;
  linkHealth?: T;
  lastCheckedAt?: T;
  isPublished?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes_select".
 */
export interface ResumesSelect<T extends boolean = true> {
  user?: T;
  isPrimary?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-sources_select".
 */
export interface JobSourcesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  sourceUrl?: T;
  feedUrl?: T;
  isVerified?: T;
  healthStatus?: T;
  integrationType?: T;
  lastCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings".
 */
export interface SystemSetting {
  id: number;
  /**
   * The timestamp up to which the automated job alert dispatcher has processed published jobs. Do not change manually unless resetting the matcher.
   */
  lastJobMatchTimestamp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  lastJobMatchTimestamp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}